In [42]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

In [26]:
df = pd.read_csv('Investment.csv')

In [27]:
df.head()

DigitalMarketing  Promotion   Research      State     Profit
0         165349.20  136897.80  471784.10  Hyderabad  192261.83
1         162597.70  151377.59  443898.53  Bangalore  191792.06
2         153441.51  101145.55  407934.54    Chennai  191050.39
3         144372.41  118671.85  383199.62  Hyderabad  182901.99
4         142107.34   91391.77  366168.42    Chennai  166187.94

In [28]:
X = df.drop(columns=['Profit'])
y = df['Profit']

In [29]:
X = pd.get_dummies(X,dtype=int)

In [30]:
X.head()

DigitalMarketing  Promotion   Research  State_Bangalore  State_Chennai  \
0         165349.20  136897.80  471784.10                0              0   
1         162597.70  151377.59  443898.53                1              0   
2         153441.51  101145.55  407934.54                0              1   
3         144372.41  118671.85  383199.62                0              0   
4         142107.34   91391.77  366168.42                0              1   

   State_Hyderabad  
0                1  
1                0  
2                0  
3                1  
4                0

In [31]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [32]:
X_train.shape,y_train.shape

((40, 6), (40,))

In [33]:
X_test.shape,y_test.shape

((10, 6), (10,))

In [34]:
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [35]:
y_pred = regressor.predict(X_test)
y_pred

array([103015.20159796, 132582.27760816, 132447.73845174,  71976.09851258,
       178537.48221055, 116161.24230165,  67851.69209676,  98791.73374687,
       113969.43533012, 167921.0656955 ])

In [36]:
m = regressor.coef_
m

array([ 7.73467193e-01,  3.28845975e-02,  3.66100259e-02,  8.66383692e+01,
       -8.72645791e+02,  7.86007422e+02])

In [37]:
c = regressor.intercept_
c

np.float64(42467.52924855311)

In [53]:
c = regressor.intercept_

X = np.append(arr = np.full((50,1),c).astype(int),values=X,axis=1)

In [54]:
X

array([[4.2467000e+04, 4.2467000e+04, 4.2467000e+04, 1.6534920e+05,
        1.3689780e+05, 4.7178410e+05, 0.0000000e+00, 0.0000000e+00,
        1.0000000e+00],
       [4.2467000e+04, 4.2467000e+04, 4.2467000e+04, 1.6259770e+05,
        1.5137759e+05, 4.4389853e+05, 1.0000000e+00, 0.0000000e+00,
        0.0000000e+00],
       [4.2467000e+04, 4.2467000e+04, 4.2467000e+04, 1.5344151e+05,
        1.0114555e+05, 4.0793454e+05, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00],
       [4.2467000e+04, 4.2467000e+04, 4.2467000e+04, 1.4437241e+05,
        1.1867185e+05, 3.8319962e+05, 0.0000000e+00, 0.0000000e+00,
        1.0000000e+00],
       [4.2467000e+04, 4.2467000e+04, 4.2467000e+04, 1.4210734e+05,
        9.1391770e+04, 3.6616842e+05, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00],
       [4.2467000e+04, 4.2467000e+04, 4.2467000e+04, 1.3187690e+05,
        9.9814710e+04, 3.6286136e+05, 0.0000000e+00, 0.0000000e+00,
        1.0000000e+00],
       [4.2467000e+04, 4.2467000e+04, 4.

In [43]:
X_opt = X[:,[0,1,2,3,4,5]]
regressor_OLS = sm.OLS(endog=y,exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                Wed, 24 Sep 2025   Prob (F-statistic):           8.51e-29
Time:                        19:52:16   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.5906      0.080      7.377      0.000       0.429       0.752
x1             0.5906      0.080      7.377      0.000       0.429       0.752
x2             0.8057      0.046     17.646      0.000       0.714       0.898
x3            -0.0268      0.052     -0.520      0.606      -0.131       0.077
x4             0.0272      0.017      1.627      0.111      -0.006       0.061
x5           -70.2265   2828.752     -0.025      0.980   -5767.625    5627.172
==============================================================================
Omnibus:                       14.785   Durbin-Watson:                   1.281
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.242
Skew:                          -0.949   Prob(JB):                     2.44e-05
Kurtosis:                       5.568   Cond. No.                     2.68e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.59e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [44]:
X_opt = X[:,[0,1,2,3,5]]
regressor_OLS = sm.OLS(endog=y,exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.948
Model:                            OLS   Adj. R-squared:                  0.944
Method:                 Least Squares   F-statistic:                     278.7
Date:                Wed, 24 Sep 2025   Prob (F-statistic):           1.68e-29
Time:                        19:57:13   Log-Likelihood:                -526.82
No. Observations:                  50   AIC:                             1062.
Df Residuals:                      46   BIC:                             1069.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.6487      0.073      8.896      0.000       0.502       0.795
x1             0.6487      0.073      8.896      0.000       0.502       0.795
x2             0.8613      0.031     27.974      0.000       0.799       0.923
x3            -0.0528      0.050     -1.058      0.296      -0.153       0.048
x4          -502.8903   2866.249     -0.175      0.861   -6272.350    5266.570
==============================================================================
Omnibus:                       14.294   Durbin-Watson:                   1.184
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               19.252
Skew:                          -0.956   Prob(JB):                     6.60e-05
Kurtosis:                       5.364   Cond. No.                     4.96e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.08e-22. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [45]:
X_opt = X[:,[0,1,2,3]]
regressor_OLS = sm.OLS(endog=y,exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.948
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     426.8
Date:                Wed, 24 Sep 2025   Prob (F-statistic):           7.29e-31
Time:                        19:57:43   Log-Likelihood:                -526.83
No. Observations:                  50   AIC:                             1060.
Df Residuals:                      47   BIC:                             1065.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.6462      0.071      9.122      0.000       0.504       0.789
x1             0.6462      0.071      9.122      0.000       0.504       0.789
x2             0.8621      0.030     28.589      0.000       0.801       0.923
x3            -0.0530      0.049     -1.073      0.289      -0.152       0.046
==============================================================================
Omnibus:                       14.678   Durbin-Watson:                   1.189
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               20.449
Skew:                          -0.961   Prob(JB):                     3.63e-05
Kurtosis:                       5.474   Cond. No.                     3.60e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 9.65e-22. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [46]:
X_opt = X[:,[0,1,3]]
regressor_OLS = sm.OLS(endog=y,exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.040
Model:                            OLS   Adj. R-squared:                  0.020
Method:                 Least Squares   F-statistic:                     2.015
Date:                Wed, 24 Sep 2025   Prob (F-statistic):              0.162
Time:                        19:58:00   Log-Likelihood:                -599.63
No. Observations:                  50   AIC:                             1203.
Df Residuals:                      48   BIC:                             1207.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.9063      0.298      3.040      0.004       0.307       1.506
x1             0.9063      0.298      3.040      0.004       0.307       1.506
x2             0.2887      0.203      1.419      0.162      -0.120       0.698
==============================================================================
Omnibus:                        0.126   Durbin-Watson:                   0.099
Prob(Omnibus):                  0.939   Jarque-Bera (JB):                0.110
Skew:                           0.093   Prob(JB):                        0.947
Kurtosis:                       2.866   Cond. No.                     1.11e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 7.68e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [47]:
X_opt = X[:,[0,1]]
regressor_OLS = sm.OLS(endog=y,exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                       nan
Date:                Wed, 24 Sep 2025   Prob (F-statistic):                nan
Time:                        19:58:13   Log-Likelihood:                -600.65
No. Observations:                  50   AIC:                             1203.
Df Residuals:                      49   BIC:                             1205.
Df Model:                           0                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.3188      0.067     19.651      0.000       1.184       1.454
x1             1.3188      0.067     19.651      0.000       1.184       1.454
==============================================================================
Omnibus:                        0.018   Durbin-Watson:                   0.020
Prob(Omnibus):                  0.991   Jarque-Bera (JB):                0.068
Skew:                           0.023   Prob(JB):                        0.966
Kurtosis:                       2.825   Cond. No.                     1.92e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.89e-22. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [49]:
bias = regressor.score(X_train,y_train)
bias

0.9501847627493607

In [50]:
variance = regressor.score(X_test,y_test)
variance

0.9347068473282424